var values = {
  'AA: Accounting': 'ACCT-AA-D',
  'AA: Business': 'BUSI-AA-D',
  'AA: Criminal Justice': 'CJUS-AA-D',
  'AA: Early Childhood Education': 'EDCE-AA-D',
  'AA: Information Systems': 'ISYS-AA-D',
  'AA: Paralegal Studies': 'PLST-AA-D',
  'AA: Psychology: Christian Counseling': 'PYCC-AA-D',
  'AA: Psychology': 'PSYC-AA-D',
  'AAS: Medical Office Assistant': 'AMOA-AAS-D',
  'BFA: Graphic Design': 'GRDG-BFA-D',
  'BS: Accounting': 'ACCT-BS-D',
  'BS: Aviation': 'AVAT-BS-D',
  'BS: Biblical and Educational Studies': 'BLES-BS-D',
  'BS: Business Administration: Automotive Dealership Management': 'BAAD-BS-D',
  'BS: Business Administration: Communications': 'BACM-BS-D',
  'BS: Business Administration: Economics': 'BAEC-BS-D',
  'BS: Business Administration: Entrepreneurship': 'BAEP-BS-D',
  'BS: Business Administration: Financial Planning': 'BAFP-BS-D',
  'BS: Business Administration: Green and Sustainable Management': 'BASM-BS-D',
  'BS: Business Administration: Healthcare Management': 'BAHC-BS-D',
  'BS: Business Administration: Human Resource Management': 'BAHR-BS-D',
  'BS: Business Administration: International Business': 'BAIB-BS-D',
  'BS: Business Administration: Leadership': 'BABL-BS-D',
  'BS: Business Administration: Marketing Analytics': 'BAMA-BS-D',
  'BS: Business Administration: Marketing: Sales Management and Professional Selling': 'BASP-BS-D',
  'BS: Criminal Justice: Business Administration and Management': 'CJBA-BS-D',
  'BS: Criminal Justice: Criminal Psychology': 'CJCP-BS-D',
  'BS: Criminal Justice: Homeland Security': 'CJHS-BS-D',
  'BS: Criminal Justice: Juvenile Justice': 'CJJJ-BS-D',
  'BS: Criminal Justice: Public Administration': 'CJPA-BS-D',
  'BS: Elementary Education in Interdisciplinary Studies': 'EDIS-BS-D',
  'BS: Government: National Security': 'GVNS-BS-D',
  'BS: Government: Politics and Policy': 'GVPP-BS-D',
  'BS: Healthcare Administration': 'HLAD-BS-D',
  'BS: Informatics: Healthcare Informatics': 'IFHC-BS-D',
  'BS: Information Systems: Data Networking': 'ISDN-BS-D',
  'BS: Information Systems: Information Assurance': 'ISIA-BS-D',
  'BS: Information Technology: Application and Database Development': 'ITAD-BS-D',
  'BS: Information Technology: Data Networking and Security': 'ITDS-BS-D',
  'BS: Information Technology: Gaming Design': 'ITGD-BS-D',
  'BS: Paralegal Studies': 'PLST-BS-D',
  'BS: Political Science': 'POSC-BS-D',
  'BS: Psychology: Addiction and Recovery': 'PYSA-BS-D',
  'BS: Psychology: Criminal Psychology': 'PSCP-BS-D',
  'BSN: Nursing for RNs: Post Licensure': 'NURP-BSN-D',
}
